stages:
    - .pre
    - build
    - test
    - deploy

build website:
    stage: build
    image: node:16-alpine
    script: 
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build

linter:
    image: node:16-alpine
    stage: .pre
    script:
        - yarn install
        - yarn lint

test website:
    image: node:16-alpine
    stage: test
    script:
        - yarn global add serve
        - apk add curl
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000 | grep "React App"

unit tests:
    image: node:16-alpine
    stage: .pre
    script:
        - yarn install
        - yarn test

deploy to S3:
    stage: deploy
    image: 
        name: amazon/aws-cli
        entrypoint: [""]
    script:
        - aws --version
