stages:
    - .pre
    - build
    - test

build website:
    stage: build
    image: node:16-alpine
    script: 
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build

.linter:
    image: node:16-alpine
    stage: .pre
    script:
        - yarn install
        - yarn lint

test website:
    image: node:16-alpine
    stage: test
    script:
#        - test -f build/index.html
        - serve -s build

.unit tests:
    image: node:16-alpine
    stage: .pre
    script:
        - yarn install
        - yarn test

