stages:
    - build
    - test

build website:
    stage: build
    image: node:16-alpine
    script: 
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build

test website:
    image: alpine
    stage: test
    script:
        - test -f /build/index.html

unit tests:
    image: node:16-alpine
    stage: test
    script:
        - yarn install
        - yarn test
      
    

